parameters:
    fortune.manager.resource.class: Fortune\ResourceBundle\Manager\ResourceManager
    fortune.access.resource_voter.class: Fortune\ResourceBundle\Voter\ResourceVoter
    fortune.access.resource_voter.resource_config: # set in extension

services:
    fortune.manager.resource:
        class: %fortune.manager.resource.class%
        arguments:
            - @doctrine.orm.entity_manager

    fortune.access.resource_voter:
        class: %fortune.access.resource_voter.class%
        public: false
        arguments:
            - %fortune.access.resource_voter.resource_config%
        tags:
            - { name: security.voter }
