parameters:
    jfortunato.manager.resource.class: JFortunato\ResourceBundle\Manager\ResourceManager
    jfortunato.access.resource_voter.class: JFortunato\ResourceBundle\Voter\ResourceVoter
    jfortunato.access.resource_voter.resource_config: # set in extension

services:
    jfortunato.manager.resource:
        class: %jfortunato.manager.resource.class%
        arguments:
            - @doctrine.orm.entity_manager

    jfortunato.access.resource_voter:
        class: %jfortunato.access.resource_voter.class%
        public: false
        arguments:
            - %jfortunato.access.resource_voter.resource_config%
        tags:
            - { name: security.voter }
